parallel (
  deploy: {
    if (env.BRANCH_NAME == 'dev') {
      node('master') {
        stage('deploy') {
          sh '''
ssh jenkins@vm-dim-web.example.com 'cd dim-web && git fetch && git reset --hard origin/dev && ./deploy-local-apache.sh'
'''
        }
      }
    }
  }
)
