#!/usr/bin/env python3

import re
import sys
import os
from flask.cli import main

if __name__ == '__main__':
    os.environ['FLASK_APP'] = os.getenv('FLASK_APP', 'dim:create_app()')
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.argv = [sys.argv[0], 'dim'] + sys.argv[1:]
    sys.exit(main())
